### ISSUE TITLE
private not working as expected

### ISSUE THREAD

**Issue by Jack-Trent** [maurits150/simploo#4]
I am using Simploo V2 and what is happening is private properties are able to be referenced in instances rather than just the class itself.

Should this be happening because I thought private properties could not be accessed like an instance member outside of the class?

```lua
namespace "Game"

class "Instance" {
    public {};

    private {
        Testing = "Accessed";
    };
}

local x = Game.Instance:new()
print(x.Testing);
-- > Returns "Accessed"
```

**Comment by maurits150** [comment]
You're right, this isn't the behavior you'd expect.

The issue is that right now private members are only working when you use them in an inheritance scenario: e.g. you have a parent class and you have a method inside a child class, trying to access a private member owned by the parent.

Accessing a private members directly (from outside the class) isn't properly handled.

I've pushed a new build that should fix this issue: https://raw.githubusercontent.com/maurits150/simploo/2.x.x/dist/simploo.lua

Could you check if this is working for you?

I've added some code that tracks the call depth of functions in classes (basically whether a call comes from outside a class or inside a class) and denies access to any private members when the call comes from outside.

**Comment by Jack-Trent** [comment]
That's fixed it, private members seem to be working correctly from what I can tell in my tests. Thanks for the prompt response and working fix.
